# Generated by Django 4.2.1 on 2025-04-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_author_bio_author_profile_picture_sport_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('Batter', 'Batter'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicketkeeper', 'Wicketkeeper'), ('Captain', 'Captain')], max_length=50)),
                ('image', models.ImageField(default='players/default.jpg', upload_to='players/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
