# Generated by Django 4.2.1 on 2025-04-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_footballteammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballteammember',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward'), ('Captain', 'Captain'), ('Vice-Captain', 'Vice-Captain'), ('Coach', 'Coach')], default='Midfielder', max_length=20),
        ),
    ]
