# Generated by Django 4.2.1 on 2025-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_stadium_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Cricket', 'Cricket'), ('Football', 'Football')], max_length=20)),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
    ]
